# Generated by Codex on 2026-09-23

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_final_taskflow_seed_data"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                django.db.models.functions.text.Lower("email"),
                name="users_email_lower_idx",
            ),
        ),
    ]
