# Generated by Codex on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["owner", "-created_at"],
                name="projects_owner_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["-created_at"], name="projects_created_idx"),
        ),
    ]
