# Generated by Codex on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assignee", "-created_at"],
                name="task_assignee_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "-created_at"],
                name="task_project_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status", "-created_at"], name="task_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assignee", "status", "-created_at"],
                name="task_assignee_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "status", "-created_at"],
                name="task_project_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["due_date", "-created_at"], name="task_due_created_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                condition=models.Q(("assignee__isnull", False), models.Q(("status", "done"), _negated=True)),
                fields=["due_date"],
                name="task_due_active_idx",
            ),
        ),
    ]
