# Generated by Django 5.2.17 on 2026-09-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_created', 'Task created'), ('task_overdue', 'Task overdue'), ('task_reassigned', 'Task reassigned'), ('task_status_changed', 'Task status changed')], max_length=32),
        ),
    ]
