# Generated by Django 5.2.17 on 2026-09-21

from django.db import migrations, models


def mark_existing_notifications_as_processed(apps, schema_editor):
    notification = apps.get_model("notifications", "Notification")
    notification.objects.update(is_read_by_system=True, is_send=True)


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_read_by_system",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_send",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            mark_existing_notifications_as_processed,
            migrations.RunPython.noop,
        ),
    ]
