# Generated by Codex on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_notification_is_read_by_system_and_is_send"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "-created_at"],
                name="notifications_user_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "task", "type"],
                name="notif_user_task_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["task", "type"], name="notif_task_type_idx"),
        ),
    ]
